---
# tasks file for jenkins

# Update package index
- name: Update apt package index
  apt:
    update_cache: yes

# Install OpenJDK 17
- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

# Verify Java installation (log output for debugging)
- name: Verify Java installation
  command: java -version
  register: java_version_output
  ignore_errors: yes
  changed_when: false
  failed_when: false
  tags: debug

# Add Jenkins repository key
- name: Add Jenkins repository key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'
    
- name: Add Jenkins repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/jenkins.list
    line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable/ binary/"
    create: yes
    
# Add Jenkins repository to sources.list
#- name: Add Jenkins repository
 # ansible.builtin.command: |
  #  echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
  #args:
   # creates: /etc/apt/sources.list.d/jenkins.list

# Update package index again
- name: Update apt package index after adding Jenkins repo
  apt:
    update_cache: yes

# Install Jenkins
- name: Install Jenkins
  apt:
    name: jenkins
    state: present

# Start Jenkins service
- name: Start Jenkins service
  service:
    name: jenkins
    state: started

# Enable Jenkins to start on boot
- name: Enable Jenkins to start on boot
  service:
    name: jenkins
    enabled: yes

# Allow port 8080 through the firewall
- name: Allow port 8080 through UFW
  ansible.builtin.command: ufw allow 8080
  register: ufw_result
  ignore_errors: true

