---
#tasks for creating a service account and binding it to the admin role
- name: Create Kubernetes service account for Jenkins
  ansible.builtin.shell:
    cmd: kubectl create --context=minikube serviceaccount jenkins
  become: true
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Create cluster role binding for Jenkins
  ansible.builtin.shell:
    cmd: kubectl create clusterrolebinding jenkins-admin --clusterrole=admin --serviceaccount=default:jenkins
  become: true
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Create Kubernetes token for Jenkins
  ansible.builtin.shell:
    cmd: kubectl create secret generic jenkins-token --from-literal=token=$(kubectl create token jenkins) --namespace=default
  become: true
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Get Jenkins token
  ansible.builtin.shell:
    cmd: kubectl get secret jenkins-token -o jsonpath='{.data.token}' | base64 --decode
  register: jenkins_token
  become: true
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config

- name: Debug Jenkins token
  ansible.builtin.debug:
    msg: "{{ jenkins_token.stdout }}"
  environment:
    KUBECONFIG: /home/ubuntu/.kube/config


